[pytest]
pythonpath = .
testpaths = tests
markers =
    users: user-related API tests
    books: book-related API tests
    orders: order-related API tests
filterwarnings =
    ignore::starlette.exceptions.StarletteDeprecationWarning
